version: "3.8"

services:
  app:
    build:
      context: ./src
    container_name: TownsleyComic
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8010:8000
    depends_on:
      - db
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: "bad_password"
    volumes:
      - townlsey_pg_data:/var/lib/postgresql/data
volumes:
  townlsey_pg_data:
