# Generated by Django 4.0.7 on 2023-12-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_remove_project_images_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='name',
        ),
    ]
