version: "3.9"
services:
  app:
    image: ghcr.io/sethangell/townsley_comic:latest
    container_name: ProdTownsleyComic
    environment:
      - S3_KEY
      - S3_SECRET_KEY
      - DJANGO_SECRET_KEY
    ports:
      - 8010:8000
    restart: always

