# Generated by Django 4.0.2 on 2022-06-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="DoubleL Studio", max_length=128),
        ),
    ]
