# Generated by Django 4.0.2 on 2022-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
