# Generated by Django 4.0.7 on 2023-08-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_domain_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
