name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Package and publish a new docker container.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
      
      - name: Install python-semantic-release
        run: python3 -m pip install python-semantic-release
      

      - name: Get next semantic version
        run: |
          next_version=$(semantic-release --noop version --print)
          echo "SEMANTIC_VERSION=$(echo $next_version)" >> $GITHUB_ENV
          echo $next_version && sleep 5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Github Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./src
          file: ./src/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/sethangell/townsley_comic:latest
            ghcr.io/sethangell/townsley_comic:${{ env.SEMANTIC_VERSION }}
          secrets: |
            SEMANTIC_VERSION=v${{ env.SEMANTIC_VERSION }}
  
  generate-semantic-release:
    name: Publish a new semantic version of this project.
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
  
 

        

